### ISSUE TITLE
Cannot use Unicode

### ISSUE THREAD

**Issue by tcanvn** [innotrade/enapso-graphdb-client#7]
Bad request error when using the Unicode in the SPARQL:
{ status: 400, message: 'HTTP Error: 400 Bad Request', success: false }.

Reproduce the issue:
`SELECT ?caythuoc ?chucnang WHERE { ?chucnang data:is_function_of data:Ngải_Cứu}`

The query works fine if "Ngải_Cứu" is changed to a non-Unicode string. I wonder if there are any parameters that allow us to use Unicode in the query.

I also check the graphDBEndpoint object. Surprisingly, it does use utf8 encoding:
requestDefaults: {
      url: 'http://localhost:7200/repositories/MyStorage',
      method: 'POST',
      encoding: 'utf8',
      headers: [Object],
      requestDefaults: [Object]
 }

**Comment by Myasir92** [comment]
Can you please update the enapso-graphdb-client package on your end and try again to run the query?

**Comment by tcanvn** [comment]
It works!
Thank you for your prompt support.
